#!/bin/bash

function php_context {
  case $DREAMFACTORY_PHP_VERSION in
    5.3) eval $1 ;;
    5.4) /usr/bin/scl enable php54 "$1" ;;
  esac
}

function update_configuration {
  # PEAR bin_dir
  local path=${OPENSHIFT_DREAMFACTORY_DIR}phplib/pear/pear

  case $DREAMFACTORY_PHP_VERSION in
    5.4)
      # SCL bin_dir
      path=$(path_append ${path:-:} $(dirname $(scl enable php54 "which php") | tr -d '\n'))

      local man_path=$(MANPATH="" scl enable php54 "printenv MANPATH")
      path_append ${MANPATH:-:} ${man_path:-:} > ${OPENSHIFT_DREAMFACTORY_DIR}env/MANPATH
      ;;
  esac

  # Composer
  path=$(path_append ${path:-:} ${OPENSHIFT_DREAMFACTORY_DIR}usr/bin)

  echo $path > ${OPENSHIFT_DREAMFACTORY_DIR}env/OPENSHIFT_PHP_PATH_ELEMENT
}
